### ISSUE TITLE
Gateway positioning inside lanes is incorrect 

### ISSUE THREAD

**Issue by sgupta1007** [christophevg/bpmn-tools#1]
**Describe the bug**
I am trying to add the exclusive gateway in lane of department 2 but is added outside the pool. I have added the code for the same

**To Reproduce**
Code

from bpmn_tools.flow          import Process, Flow, Lane
from bpmn_tools.flow          import End,UserTask, ScriptTask, MessageFlow,SendTask,Task,ExclusiveGateway
from bpmn_tools.collaboration import Collaboration, Participant
from bpmn_tools.notation      import Definitions
from bpmn_tools.diagrams      import Diagram, Plane
from bpmn_tools.layout        import simple
from bpmn_tools.util          import model2xml

a=SendTask('A')
b=ScriptTask('B')
decision=ExclusiveGateway("Decision")
c=SendTask('C')
d=Task('D')
e=Task('E')
f=End('F')

lane1=Lane('Department 1')
lane2=Lane('Department 2')

lane1.append(a).append(c).append(d).append(e)
lane2.append(b).append(decision).append(f)

flow1=Flow(source=a,target=b)
flow2=Flow(source=b,target=decision)
flow3=Flow(source=decision,target=c,name='Yes')
flow4=Flow(source=decision,target=f,name='No')
flow5=Flow(source=c,target=d)
flow6=Flow(source=d,target=e)

process1=Process().append(lane1).append(lane2).append(flow1).append(flow2).append(flow3).append(flow4).append(flow5).append(flow6)

collaboration=Collaboration(id='Colaboration').extend([
    Participant('Corporation ',process1,id="p1")
    Participant('Employee',id='p2')
])

definitions = Definitions(id="definitions").extend([
  process1,
  collaboration
])

definitions.append(
  Diagram(
    id="diagram",
    plane=Plane(id="plane", element=collaboration)
  )
)

simple.layout(definitions)

print(model2xml(definitions))

**Expected behavior**
I have attached the diagram below .First one is the diagram produced using bpmn-tools and second one is the expected diagram prepared using graphical editor

**Screenshots**

<img width="847" alt="bpmn_bug" src="https://github.com/christophevg/bpmn-tools/assets/101873081/274c6172-4ea3-466f-a380-78b6ad5991e3">

**Comment by christophevg** [comment]
Hi sgupta1007,

Thanks for the submission and the clear description + good example illustrating the problem.
I've turned your issue into a branch with a "failing" test and will implement a fix as soon as possible (given the year ending/holidays, it might take me a few days to get to addressing some time to it 😇)

Some background: Simple layout is "simple" and even already a bit "old". I haven't kept it in sync with the added element beyond Tasks 🙄 So, it simply doesn't take the gateway into account, which keeps it at position (0,0).

To be continued!
Christophe

**Comment by christophevg** [comment]
Ok, that was even easier that I anticipated 😉
The fix was too simple not to apply it right now.
Version 0.9.3 introduces support for simple layout and gateways.

**Comment by sgupta1007** [comment]
<img width="762" alt="bpmn_bug2" src="https://github.com/christophevg/bpmn-tools/assets/101873081/aacee93d-2298-4787-ba09-625d061cc0dc">


This is what I am getting after installing the new version .

**Comment by sgupta1007** [comment]
Can you please also introduce support to multiple pools for a single process.

**Comment by christophevg** [comment]
> This is what I am getting after installing the new version .

Did you forget to apply the `simple.layout`?

Because your code (minus the second participant) ...

```python
  from bpmn_tools.flow import Process, Flow, Lane
  from bpmn_tools.flow import End, ScriptTask, SendTask,Task,ExclusiveGateway
  from bpmn_tools.collaboration import Collaboration, Participant
  from bpmn_tools.notation import Definitions
  from bpmn_tools.diagrams import Diagram, Plane
  from bpmn_tools.layout import simple

  a=SendTask('A')
  b=ScriptTask('B')
  decision=ExclusiveGateway("Decision")
  c=SendTask('C')
  d=Task('D')
  e=Task('E')
  f=End('F')

  lane1=Lane('Department 1')
  lane2=Lane('Department 2')

  lane1.append(a).append(c).append(d).append(e)
  lane2.append(b).append(decision).append(f)

  flow1=Flow(source=a,target=b)
  flow2=Flow(source=b,target=decision)
  flow3=Flow(source=decision,target=c,name='Yes')
  flow4=Flow(source=decision,target=f,name='No')
  flow5=Flow(source=c,target=d)
  flow6=Flow(source=d,target=e)

  process1=Process().append(lane1).append(lane2).append(flow1).append(flow2).append(flow3).append(flow4).append(flow5).append(flow6)

  collaboration=Collaboration(id='Colaboration').extend([
    Participant('Corporation ',process1,id="p1")
  ])

  definitions = Definitions(id="definitions").extend([
    process1,
    collaboration
  ])

  definitions.append(
    Diagram( id="diagram", plane=Plane(id="plane", element=collaboration) )
  )

  simple.layout(definitions)
```

renders as...

<img width="883" alt="image" src="https://github.com/christophevg/bpmn-tools/assets/124216/801893c0-3ed0-43dd-9ca1-253b8d80d5f5">

**Comment by sgupta1007** [comment]
Thanks for resolving this issue.

**Comment by christophevg** [comment]
> Can you please also introduce support to multiple pools for a single process.

I assume you refer to support for `childLaneSet`:

<img width="464" alt="image" src="https://github.com/christophevg/bpmn-tools/assets/124216/4b316bf2-08ef-4b45-b210-f35a553b638b">

```xml
  <bpmn:process id="Process_1" isExecutable="true">
    <bpmn:laneSet id="LaneSet_1ftxl4s">
      <bpmn:lane id="Lane_1" />
      <bpmn:lane id="Lane_2" name="lane">
        <bpmn:childLaneSet id="LaneSet_1">
          <bpmn:lane id="Lane_2_1" />
          <bpmn:lane id="Lane_2_2" name="child lane" />
        </bpmn:childLaneSet>
      </bpmn:lane>
    </bpmn:laneSet>
  </bpmn:process>
```

👉 Please don't mix issues. Create another issue to request the addition of support for that feature, clearly indicating what you want/expect, with a clear example. Thanks!
