### ISSUE TITLE
UserTask throwing error inside the Process

### ISSUE THREAD

**Issue by sgupta1007** [christophevg/bpmn-tools#3]
**Describe the bug**
I am trying to add task type instead of simple tag in Branch inside a process .Code instead of producing correct diagram is producing bug

**Code**
Code using BPMN to produce the bug
```

from bpmn_tools.builder.process import Process, Task, Branch, BranchKind, If
from bpmn_tools import flow
from bpmn_tools.flow import UserTask
from bpmn_tools.colors import Green, Blue, Red, Orange
from bpmn_tools.util import model2xml

process=Process([
Task(name='Help'),
Branch([Task(name='Branch one a'),Task(name='Branch one b')],kind=BranchKind.AND),
Branch([Task(name='Branch nested before'),Branch([UserTask(name='Inside nested branch')],kind=BranchKind.XOR),Task(name='Branch nested after')],kind=BranchKind.OR)
],name='Some random process',starts=True,ends=True)

  
model=process.render()

definations=model2xml(model)
```

**Expected behavior**
I am expecting this diagram 
<img width="898" alt="bpmn_bug_new_1" src="https://github.com/christophevg/bpmn-tools/assets/101873081/1fb8b2bf-67f4-4d62-8356-aca895043aea">

**Original behavior**

<img width="553" alt="bpmn_bug_new_2" src="https://github.com/christophevg/bpmn-tools/assets/101873081/18e3b36b-afb7-4af1-ac0c-13a778d7d50f">

**Comment by christophevg** [comment]
The API of Process Builder doesn't accept flow.Element, it accepts Process Builder Tasks, and such task has a `cls` argument, which allows you to specify the flow.Element, e.g. `UserTask` so just change:

`UserTask(name='Inside nested branch')`

into

`Task(name='Inside nested branch', cls=UserTask)`

and you get:

<img width="1020" alt="image" src="https://github.com/christophevg/bpmn-tools/assets/124216/148e18cd-60de-424d-873d-a3e2209c3533">
